# Generated by Django 2.2.16 on 2022-04-10 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Поле не соответствует требованиям^ ^[-a-zA-Z0-9_]+$', regex='^[-a-zA-Z0-9_]+$')], verbose_name='URL_Genres'),
        ),
    ]
